name: hsma_reproducible_reporting
channels:
    - conda-forge
dependencies:
    - python=3.11.9
    - pip
    - pip:
        - pyyaml
        - nbformat>=4.2.0
        - nbclient
        - pandas==2.2.2
        - numpy==1.26.4
        - simpy==4.0.2
        - matplotlib==3.9.1.post1
        - plotly==5.23.0
        - folium==0.17.0
        - geopandas==1.0.1
        - ipykernel==6.29.5
        - ipython==8.27.0
        - openpyxl
        - palmerpenguins==0.1.4
        - papermill<=2.6.0
        - itables>=2.0.0,<=2.2.1
        - great_tables>=0.11.0
        - seaborn>=0.13.0
        - quarto==0.1.0
        - jupyter==1.1.1
        - xlsxwriter==3.2.0
