[project]
authors = ["lh <vitygas@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "manim"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
