name: hsma_forecast
channels:
  - conda-forge
dependencies:
  - ipykernel
  - pip=21.0.1
  - python=3.11.4
  - pip:
    - numpy==1.26.4
    - pandas>=1.3.4, <=1.5.3
    - forecast-tools==0.3.0
    - ipywidgets==7.6.5
    - matplotlib>=3.5.0
    - notebook==6.0.3
    - scikit-learn>=1.0.1
    - scipy>=1.7.3
    - seaborn>=0.11.2
    - statsmodels>=0.11.1
    - plotly>=5.4.0, <=5.19.0
    - prophet==1.1.5
